name: Checkov

on:
 push:
  branches:
      - 'fix*/*'
      - 'feat*/*'
      - 'hotfix*/*'
      - 'release*/*'

permissions:
  contents: read

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          download_external_modules: true
          github_pat: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_OVERRIDE_URL: true  # optional: this can be used to instruct the action to override the global GIT config to inject the PAT to the URL
