name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get Merged PR Labels
        id: get-merged-pr-labels
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Drafts the next Release notes as Pull Requests are merged into "main"
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
           config-name: configs/release-drafter.yml
           disable-autolabeler: true
           publish : ${{ !contains(fromJSON('["no-release", "chore", "automation"]'), steps.get-merged-pr-labels.outputs.labels) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
